import Link from "next/link";
import { notFound } from "next/navigation";
import { ItemHistoryChart } from "@/components/charts/item-history-chart";
import { StatusBadge } from "@/components/inventory/status-badge";
import { mockInventory } from "@/lib/mock/inventory";
export function generateStaticParams() { return mockInventory.map((item) => ({ inventoryItemId: item.inventoryItemId })); }
export default async function InventoryDetail({ params }: { params: Promise<{ inventoryItemId: string }> }) { const { inventoryItemId } = await params; const item = mockInventory.find((value) => value.inventoryItemId === inventoryItemId); if (!item) notFound(); const history = [{ date: "25 Jul", inventory: item.dayBeforeYesterday }, { date: "26 Jul", inventory: item.yesterday }, { date: "27 Jul", inventory: item.today }]; return <div className="space-y-6"><Link href="/inventory" className="text-xs font-semibold text-[#246552]">← Back to inventory</Link><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><div className="grid size-16 place-items-center rounded-xl bg-[#f2eee3] text-xl font-semibold text-[#8f7c45]">{item.productTitle[0]}</div><div><h1 className="text-2xl font-semibold text-slate-900">{item.productTitle}</h1><p className="mt-1 text-sm text-slate-500">{item.variantTitle} · {item.sku ?? "No SKU"}</p></div></div><StatusBadge status={item.status}/></div><section className="grid gap-4 sm:grid-cols-3"><Metric label="Current stock" value={item.today}/><Metric label="Yesterday" value={item.yesterday} change={item.todayChange}/><Metric label="Day before yesterday" value={item.dayBeforeYesterday} change={item.threeDayChange}/></section><section className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-800">Inventory history</h2><p className="mt-1 text-xs text-slate-400">Three-day stock trend</p><div className="mt-5"><ItemHistoryChart values={history}/></div></div><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-800">Inventory details</h2><dl className="mt-4 space-y-4"><Detail label="Location" value={item.locationName}/><Detail label="Product ID" value={item.productId}/><Detail label="Variant ID" value={item.variantId}/><Detail label="Inventory item ID" value={item.inventoryItemId}/><Detail label="Location ID" value={item.locationId}/></dl></div></section></div>; }
function Metric({ label, value, change }: { label: string; value: number; change?: number }) { return <div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p>{change !== undefined && <p className={`mt-2 text-xs ${change > 0 ? "text-emerald-600" : change < 0 ? "text-red-600" : "text-slate-400"}`}>{change > 0 ? "+" : ""}{change} units</p>}</div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 break-all text-xs text-slate-700">{value}</dd></div>; }
