import { connection } from "next/server";
import { requireDashboardSession } from "@/lib/auth/authorization";
import { getInventoryFeed, type InventoryFeed } from "@/lib/inventory/live-data";
import { fetchSalesReport } from "@/services/shopify-sales";
import type { SalesReport } from "@/types/sales";

const money = (value: number, currency: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);
async function loadSales(): Promise<{ report: SalesReport | null; inventory: InventoryFeed | null; error: string | null }> {
  try { const [report, inventory] = await Promise.all([fetchSalesReport(30), getInventoryFeed()]); return { report, inventory, error: null }; }
  catch (error) { return { report: null, inventory: null, error: error instanceof Error ? error.message : "Orders could not be loaded." }; }
}

export default async function SalesPage() {
  await requireDashboardSession(); await connection(); const result = await loadSales();
  if (!result.report || !result.inventory) return <div className="rounded-xl border border-amber-200 bg-amber-50 p-6"><h1 className="text-xl font-semibold text-slate-900">Sales analytics needs Shopify order access</h1><p className="mt-2 text-sm text-slate-700">Release a new Shopify app version with <code>read_orders</code>, then approve the updated access on Vasudha Foods. Inventory features remain available.</p><p className="mt-2 text-xs text-slate-500">{result.error}</p></div>;
  const report = result.report; const stockByProduct = new Map<string, number>(); for (const item of result.inventory.items) stockByProduct.set(item.productId, (stockByProduct.get(item.productId) ?? 0) + item.today);
  return <div className="space-y-6"><div><p className="text-xs font-medium text-[#2d725f]">Commerce intelligence</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Sales, orders and stock</h1><p className="mt-1 text-sm text-slate-500">{report.from} to {report.to}. The 30-day forecast is a simple run-rate projection.</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Orders" value={report.orders}/><Metric label="Net revenue" value={money(report.netRevenue, report.currency)}/><Metric label="Average order value" value={money(report.averageOrderValue, report.currency)}/><Metric label="30-day forecast" value={money(report.projected30DayRevenue, report.currency)}/><Metric label="Refunds" value={money(report.refunds, report.currency)}/><Metric label="Cancellations" value={report.cancelledOrders}/></section><section className="grid gap-5 xl:grid-cols-2"><ProductTable title="Best-selling products" products={report.products.slice(0, 10)} stock={stockByProduct}/><ProductTable title="Slow-moving products" products={[...report.products].sort((a, b) => a.units - b.units).slice(0, 10)} stock={stockByProduct}/></section><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="text-sm font-semibold">Daily orders and revenue</h2></div><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-400"><tr><th className="px-5 py-3">Date</th><th className="text-right">Orders</th><th className="text-right">Revenue</th><th className="px-5 text-right">Refunds</th></tr></thead><tbody>{report.daily.map((day) => <tr key={day.date} className="border-t border-slate-100"><td className="px-5 py-2">{day.date}</td><td className="text-right">{day.orders}</td><td className="text-right">{money(day.revenue, report.currency)}</td><td className="px-5 text-right text-red-600">{money(day.refunds, report.currency)}</td></tr>)}</tbody></table></div></div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold text-slate-900">{value}</p></div>; }
function ProductTable({ title, products, stock }: { title: string; products: SalesReport["products"]; stock: Map<string, number> }) { return <div className="rounded-xl border border-slate-200 bg-white"><h2 className="border-b border-slate-100 p-5 text-sm font-semibold">{title}</h2><div className="divide-y divide-slate-100">{products.map((product) => <div key={product.productId ?? product.title} className="flex items-center gap-3 px-5 py-3 text-xs"><span className="min-w-0 flex-1 truncate font-semibold text-slate-700">{product.title}</span><span>{product.units} sold</span><span className="w-20 text-right text-slate-500">{product.productId ? stock.get(product.productId) ?? 0 : "—"} stock</span></div>)}</div></div>; }
